# Generated by Django 3.0.8 on 2020-07-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('e_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('e_contact', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.IntegerField(),
        ),
    ]
