# Generated by Django 3.0.8 on 2020-09-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_auto_20200718_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='newfolder/')),
                ('image_bin', models.BinaryField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
